title: Radosław Skupnik's blog
author: Radosław Skupnik
description: A blog on various topics related to programming

highlighter: null
permalink: /:title

url: https://myzopotamia.dev
baseurl: 

sass:
  sass_dir: public/css
  style: :compressed
  
show_drafts: false

matomo_analytics:
  url: stats.myzopotamia.dev
  siteId: "1"
