title: Radosław Skupnik's blog
author: Radosław Skupnik
description: A blog on various topics related to programming

highlighter: null
permalink: /:title

url: https://rskupnik.github.io
baseurl: 

sass:
  sass_dir: public/css
  style: :compressed
  
show_drafts: false

# Google services
google_analytics: G-X5RCN5WZEZ